### PR TITLE
This is my sections-Toan dao

### PR DESCRIPTION
**Pull request by potatobeannato**
This is what i did for my two pages

### CODE REVIEW

**Review by mccallkaley — APPROVED** [review]

**Review by potatobeannato — COMMENTED** [review]
I just change it

**Review by Alldarwish — APPROVED** [review]
Looks cleaned up. Make sure to check again once McCall adds her sections.

**Review by Alldarwish — CHANGES_REQUESTED** [review]
Are you adding new images? I thought all images are already in the repo.

**Comment by Alldarwish** [comment]
Will wait for all changes to be applied first.

**Pull request closed without merging**
